# Generated by Django 4.1.5 on 2023-01-12 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', max_length=600)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, choices=[('movie', 'movie'), ('food', 'food'), ('medical', 'medical')], default='', max_length=50)),
                ('shared_users', models.ManyToManyField(related_name='owe_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
